coverage:
  status:
    project:
      default:
        informational: false
    patch:
      default:
        informational: false
comment: off

fixes:
  - "dbatools/::bin/projects/dbatools/dbatools/"

